export enum enAppSession {
    user_id,
    fullname,
    username,
    email_id,
    mobilenumber,
    client_id,
    clientname,
    project_id,
    projectname,
    society_id,
    society_name,
    complex_id,
    complex_name,
    wing_id,
    wing_name,
    authorisedmodule,
    authority,
    haslogin,
    password,
    clientlist,
    projectlist,
    usermodulelist,
    usermaster_id,
    profilepicture,
    portal_config
    // userData,
}